spring.application.name=ConfigModule
server.port=8888
spring.cloud.config.server.native.search-locations=file:///D:/Teach/Java/Warehouse/Config/Cloud/
spring.cloud.config.server.encrypt.enabled=false
spring.profiles.active=native
spring.security.user.name=root
spring.security.user.password=s3cr3t