spring.application.name=api-gateway
server.port=8765
spring.profiles.active=development
spring.config.import=configserver:http://localhost:8888
spring.cloud.config.username=root
spring.cloud.config.password=s3cr3t
